export const menshQuran = [
  { "id": 1, "name": "الفاتحة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/001.mp3" },
  { "id": 2, "name": "البقرة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/002.mp3" },
  { "id": 3, "name": "آل عمران", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/003.mp3" },
  { "id": 4, "name": "النساء", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/004.mp3" },
  { "id": 5, "name": "المائدة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/005.mp3" },
  { "id": 6, "name": "الأنعام", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/006.mp3" },
  { "id": 7, "name": "الأعراف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/007.mp3" },
  { "id": 8, "name": "الأنفال", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/008.mp3" },
  { "id": 9, "name": "التوبة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/009.mp3" },
  { "id": 10, "name": "يونس", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/010.mp3" },
  { "id": 11, "name": "هود", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/011.mp3" },
  { "id": 12, "name": "يوسف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/012.mp3" },
  { "id": 13, "name": "الرعد", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/013.mp3" },
  { "id": 14, "name": "إبراهيم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/014.mp3" },
  { "id": 15, "name": "الحجر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/015.mp3" },
  { "id": 16, "name": "النحل", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/016.mp3" },
  { "id": 17, "name": "الإسراء", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/017.mp3" },
  { "id": 18, "name": "الكهف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/018.mp3" },
  { "id": 19, "name": "مريم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/019.mp3" },
  { "id": 20, "name": "طه", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/020.mp3" },
  { "id": 21, "name": "الأنبياء", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/021.mp3" },
  { "id": 22, "name": "الحج", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/022.mp3" },
  { "id": 23, "name": "المؤمنون", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/023.mp3" },
  { "id": 24, "name": "النور", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/024.mp3" },
  { "id": 25, "name": "الفرقان", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/025.mp3" },
  { "id": 26, "name": "الشعراء", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/026.mp3" },
  { "id": 27, "name": "النمل", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/027.mp3" },
  { "id": 28, "name": "القصص", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/028.mp3" },
  { "id": 29, "name": "العنكبوت", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/029.mp3" },
  { "id": 30, "name": "الروم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/030.mp3" },
  { "id": 31, "name": "لقمان", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/031.mp3" },
  { "id": 32, "name": "السجدة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/032.mp3" },
  { "id": 33, "name": "الأحزاب", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/033.mp3" },
  { "id": 34, "name": "سبإ", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/034.mp3" },
  { "id": 35, "name": "فاطر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/035.mp3" },
  { "id": 36, "name": "يس", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/036.mp3" },
  { "id": 37, "name": "الصافات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/037.mp3" },
  { "id": 38, "name": "ص", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/038.mp3" },
  { "id": 39, "name": "الزمر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/039.mp3" },
  { "id": 40, "name": "غافر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/040.mp3" },
  { "id": 41, "name": "فصلت", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/041.mp3" },
  { "id": 42, "name": "الشورى", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/042.mp3" },
  { "id": 43, "name": "الزخرف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/043.mp3" },
  { "id": 44, "name": "الدخان", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/044.mp3" },
  { "id": 45, "name": "الجاثية", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/045.mp3" },
  { "id": 46, "name": "الأحقاف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/046.mp3" },
  { "id": 47, "name": "محمد", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/047.mp3" },
  { "id": 48, "name": "الفتح", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/048.mp3" },
  { "id": 49, "name": "الحجرات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/049.mp3" },
  { "id": 50, "name": "ق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/050.mp3" },
  { "id": 51, "name": "الذاريات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/051.mp3" },
  { "id": 52, "name": "الطور", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/052.mp3" },
  { "id": 53, "name": "النجم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/053.mp3" },
  { "id": 54, "name": "القمر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/054.mp3" },
  { "id": 55, "name": "الرحمن", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/055.mp3" },
  { "id": 56, "name": "الواقعة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/056.mp3" },
  { "id": 57, "name": "الحديد", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/057.mp3" },
  { "id": 58, "name": "المجادلة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/058.mp3" },
  { "id": 59, "name": "الحشر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/059.mp3" },
  { "id": 60, "name": "الممتحنة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/060.mp3" },
  { "id": 61, "name": "الصف", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/061.mp3" },
  { "id": 62, "name": "الجمعة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/062.mp3" },
  { "id": 63, "name": "المنافقون", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/063.mp3" },
  { "id": 64, "name": "التغابن", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/064.mp3" },
  { "id": 65, "name": "الطلاق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/065.mp3" },
  { "id": 66, "name": "التحريم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/066.mp3" },
  { "id": 67, "name": "الملك", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/067.mp3" },
  { "id": 68, "name": "القلم", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/068.mp3" },
  { "id": 69, "name": "الحاقة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/069.mp3" },
  { "id": 70, "name": "المعارج", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/070.mp3" },
  { "id": 71, "name": "نوح", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/071.mp3" },
  { "id": 72, "name": "الجن", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/072.mp3" },
  { "id": 73, "name": "المزمل", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/073.mp3" },
  { "id": 74, "name": "المدثر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/074.mp3" },
  { "id": 75, "name": "القيامة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/075.mp3" },
  { "id": 76, "name": "الإنسان", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/076.mp3" },
  { "id": 77, "name": "المرسلات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/077.mp3" },
  { "id": 78, "name": "النبأ", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/078.mp3" },
  { "id": 79, "name": "النازعات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/079.mp3" },
  { "id": 80, "name": "عبس", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/080.mp3" },
  { "id": 81, "name": "التكوير", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/081.mp3" },
  { "id": 82, "name": "الإنفطار", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/082.mp3" },
  { "id": 83, "name": "المطففين", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/083.mp3" },
  { "id": 84, "name": "الإنشقاق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/084.mp3" },
  { "id": 85, "name": "البروج", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/085.mp3" },
  { "id": 86, "name": "الطارق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/086.mp3" },
  { "id": 87, "name": "الأعلى", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/087.mp3" },
  { "id": 88, "name": "الغاشية", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/088.mp3" },
  { "id": 89, "name": "الفجر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/089.mp3" },
  { "id": 90, "name": "البلد", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/090.mp3" },
  { "id": 91, "name": "الشمس", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/091.mp3" },
  { "id": 92, "name": "الليل", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/092.mp3" },
  { "id": 93, "name": "الضحى", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/093.mp3" },
  { "id": 94, "name": "الشرح", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/094.mp3" },
  { "id": 95, "name": "التين", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/095.mp3" },
  { "id": 96, "name": "العلق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/096.mp3" },
  { "id": 97, "name": "القدر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/097.mp3" },
  { "id": 98, "name": "البينة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/098.mp3" },
  { "id": 99, "name": "الزلزلة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/099.mp3" },
  { "id": 100, "name": "العاديات", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/100.mp3" },
  { "id": 101, "name": "القارعة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/101.mp3" },
  { "id": 102, "name": "التكاثر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/102.mp3" },
  { "id": 103, "name": "العصر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/103.mp3" },
  { "id": 104, "name": "الهمزة", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/104.mp3" },
  { "id": 105, "name": "الفيل", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/105.mp3" },
  { "id": 106, "name": "قريش", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/106.mp3" },
  { "id": 107, "name": "الماعون", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/107.mp3" },
  { "id": 108, "name": "الكوثر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/108.mp3" },
  { "id": 109, "name": "الكافرون", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/109.mp3" },
  { "id": 110, "name": "النصر", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/110.mp3" },
  { "id": 111, "name": "المسد", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/111.mp3" },
  { "id": 112, "name": "الإخلاص", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/112.mp3" },
  { "id": 113, "name": "الفلق", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/113.mp3" },
  { "id": 114, "name": "الناس", "url": "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/114.mp3" }
]
export const menshQuranMurattal = [
  { "id": 1, "name": "الفاتحة", "url": "https://server10.mp3quran.net/minsh/001.mp3" },
  { "id": 2, "name": "البقرة", "url": "https://server10.mp3quran.net/minsh/002.mp3" },
  { "id": 3, "name": "آل عمران", "url": "https://server10.mp3quran.net/minsh/003.mp3" },
  { "id": 4, "name": "النساء", "url": "https://server10.mp3quran.net/minsh/004.mp3" },
  { "id": 5, "name": "المائدة", "url": "https://server10.mp3quran.net/minsh/005.mp3" },
  { "id": 6, "name": "الأنعام", "url": "https://server10.mp3quran.net/minsh/006.mp3" },
  { "id": 7, "name": "الأعراف", "url": "https://server10.mp3quran.net/minsh/007.mp3" },
  { "id": 8, "name": "الأنفال", "url": "https://server10.mp3quran.net/minsh/008.mp3" },
  { "id": 9, "name": "التوبة", "url": "https://server10.mp3quran.net/minsh/009.mp3" },
  { "id": 10, "name": "يونس", "url": "https://server10.mp3quran.net/minsh/010.mp3" },
  { "id": 11, "name": "هود", "url": "https://server10.mp3quran.net/minsh/011.mp3" },
  { "id": 12, "name": "يوسف", "url": "https://server10.mp3quran.net/minsh/012.mp3" },
  { "id": 13, "name": "الرعد", "url": "https://server10.mp3quran.net/minsh/013.mp3" },
  { "id": 14, "name": "إبراهيم", "url": "https://server10.mp3quran.net/minsh/014.mp3" },
  { "id": 15, "name": "الحجر", "url": "https://server10.mp3quran.net/minsh/015.mp3" },
  { "id": 16, "name": "النحل", "url": "https://server10.mp3quran.net/minsh/016.mp3" },
  { "id": 17, "name": "الإسراء", "url": "https://server10.mp3quran.net/minsh/017.mp3" },
  { "id": 18, "name": "الكهف", "url": "https://server10.mp3quran.net/minsh/018.mp3" },
  { "id": 19, "name": "مريم", "url": "https://server10.mp3quran.net/minsh/019.mp3" },
  { "id": 20, "name": "طه", "url": "https://server10.mp3quran.net/minsh/020.mp3" },
  { "id": 21, "name": "الأنبياء", "url": "https://server10.mp3quran.net/minsh/021.mp3" },
  { "id": 22, "name": "الحج", "url": "https://server10.mp3quran.net/minsh/022.mp3" },
  { "id": 23, "name": "المؤمنون", "url": "https://server10.mp3quran.net/minsh/023.mp3" },
  { "id": 24, "name": "النور", "url": "https://server10.mp3quran.net/minsh/024.mp3" },
  { "id": 25, "name": "الفرقان", "url": "https://server10.mp3quran.net/minsh/025.mp3" },
  { "id": 26, "name": "الشعراء", "url": "https://server10.mp3quran.net/minsh/026.mp3" },
  { "id": 27, "name": "النمل", "url": "https://server10.mp3quran.net/minsh/027.mp3" },
  { "id": 28, "name": "القصص", "url": "https://server10.mp3quran.net/minsh/028.mp3" },
  { "id": 29, "name": "العنكبوت", "url": "https://server10.mp3quran.net/minsh/029.mp3" },
  { "id": 30, "name": "الروم", "url": "https://server10.mp3quran.net/minsh/030.mp3" },
  { "id": 31, "name": "لقمان", "url": "https://server10.mp3quran.net/minsh/031.mp3" },
  { "id": 32, "name": "السجدة", "url": "https://server10.mp3quran.net/minsh/032.mp3" },
  { "id": 33, "name": "الأحزاب", "url": "https://server10.mp3quran.net/minsh/033.mp3" },
  { "id": 34, "name": "سبإ", "url": "https://server10.mp3quran.net/minsh/034.mp3" },
  { "id": 35, "name": "فاطر", "url": "https://server10.mp3quran.net/minsh/035.mp3" },
  { "id": 36, "name": "يس", "url": "https://server10.mp3quran.net/minsh/036.mp3" },
  { "id": 37, "name": "الصافات", "url": "https://server10.mp3quran.net/minsh/037.mp3" },
  { "id": 38, "name": "ص", "url": "https://server10.mp3quran.net/minsh/038.mp3" },
  { "id": 39, "name": "الزمر", "url": "https://server10.mp3quran.net/minsh/039.mp3" },
  { "id": 40, "name": "غافر", "url": "https://server10.mp3quran.net/minsh/040.mp3" },
  { "id": 41, "name": "فصلت", "url": "https://server10.mp3quran.net/minsh/041.mp3" },
  { "id": 42, "name": "الشورى", "url": "https://server10.mp3quran.net/minsh/042.mp3" },
  { "id": 43, "name": "الزخرف", "url": "https://server10.mp3quran.net/minsh/043.mp3" },
  { "id": 44, "name": "الدخان", "url": "https://server10.mp3quran.net/minsh/044.mp3" },
  { "id": 45, "name": "الجاثية", "url": "https://server10.mp3quran.net/minsh/045.mp3" },
  { "id": 46, "name": "الأحقاف", "url": "https://server10.mp3quran.net/minsh/046.mp3" },
  { "id": 47, "name": "محمد", "url": "https://server10.mp3quran.net/minsh/047.mp3" },
  { "id": 48, "name": "الفتح", "url": "https://server10.mp3quran.net/minsh/048.mp3" },
  { "id": 49, "name": "الحجرات", "url": "https://server10.mp3quran.net/minsh/049.mp3" },
  { "id": 50, "name": "ق", "url": "https://server10.mp3quran.net/minsh/050.mp3" },
  { "id": 51, "name": "الذاريات", "url": "https://server10.mp3quran.net/minsh/051.mp3" },
  { "id": 52, "name": "الطور", "url": "https://server10.mp3quran.net/minsh/052.mp3" },
  { "id": 53, "name": "النجم", "url": "https://server10.mp3quran.net/minsh/053.mp3" },
  { "id": 54, "name": "القمر", "url": "https://server10.mp3quran.net/minsh/054.mp3" },
  { "id": 55, "name": "الرحمن", "url": "https://server10.mp3quran.net/minsh/055.mp3" },
  { "id": 56, "name": "الواقعة", "url": "https://server10.mp3quran.net/minsh/056.mp3" },
  { "id": 57, "name": "الحديد", "url": "https://server10.mp3quran.net/minsh/057.mp3" },
  { "id": 58, "name": "المجادلة", "url": "https://server10.mp3quran.net/minsh/058.mp3" },
  { "id": 59, "name": "الحشر", "url": "https://server10.mp3quran.net/minsh/059.mp3" },
  { "id": 60, "name": "الممتحنة", "url": "https://server10.mp3quran.net/minsh/060.mp3" },
  { "id": 61, "name": "الصف", "url": "https://server10.mp3quran.net/minsh/061.mp3" },
  { "id": 62, "name": "الجمعة", "url": "https://server10.mp3quran.net/minsh/062.mp3" },
  { "id": 63, "name": "المنافقون", "url": "https://server10.mp3quran.net/minsh/063.mp3" },
  { "id": 64, "name": "التغابن", "url": "https://server10.mp3quran.net/minsh/064.mp3" },
  { "id": 65, "name": "الطلاق", "url": "https://server10.mp3quran.net/minsh/065.mp3" },
  { "id": 66, "name": "التحريم", "url": "https://server10.mp3quran.net/minsh/066.mp3" },
  { "id": 67, "name": "الملك", "url": "https://server10.mp3quran.net/minsh/067.mp3" },
  { "id": 68, "name": "القلم", "url": "https://server10.mp3quran.net/minsh/068.mp3" },
  { "id": 69, "name": "الحاقة", "url": "https://server10.mp3quran.net/minsh/069.mp3" },
  { "id": 70, "name": "المعارج", "url": "https://server10.mp3quran.net/minsh/070.mp3" },
  { "id": 71, "name": "نوح", "url": "https://server10.mp3quran.net/minsh/071.mp3" },
  { "id": 72, "name": "الجن", "url": "https://server10.mp3quran.net/minsh/072.mp3" },
  { "id": 73, "name": "المزمل", "url": "https://server10.mp3quran.net/minsh/073.mp3" },
  { "id": 74, "name": "المدثر", "url": "https://server10.mp3quran.net/minsh/074.mp3" },
  { "id": 75, "name": "القيامة", "url": "https://server10.mp3quran.net/minsh/075.mp3" },
  { "id": 76, "name": "الإنسان", "url": "https://server10.mp3quran.net/minsh/076.mp3" },
  { "id": 77, "name": "المرسلات", "url": "https://server10.mp3quran.net/minsh/077.mp3" },
  { "id": 78, "name": "النبأ", "url": "https://server10.mp3quran.net/minsh/078.mp3" },
  { "id": 79, "name": "النازعات", "url": "https://server10.mp3quran.net/minsh/079.mp3" },
  { "id": 80, "name": "عبس", "url": "https://server10.mp3quran.net/minsh/080.mp3" },
  { "id": 81, "name": "التكوير", "url": "https://server10.mp3quran.net/minsh/081.mp3" },
  { "id": 82, "name": "الإنفطار", "url": "https://server10.mp3quran.net/minsh/082.mp3" },
  { "id": 83, "name": "المطففين", "url": "https://server10.mp3quran.net/minsh/083.mp3" },
  { "id": 84, "name": "الإنشقاق", "url": "https://server10.mp3quran.net/minsh/084.mp3" },
  { "id": 85, "name": "البروج", "url": "https://server10.mp3quran.net/minsh/085.mp3" },
  { "id": 86, "name": "الطارق", "url": "https://server10.mp3quran.net/minsh/086.mp3" },
  { "id": 87, "name": "الأعلى", "url": "https://server10.mp3quran.net/minsh/087.mp3" },
  { "id": 88, "name": "الغاشية", "url": "https://server10.mp3quran.net/minsh/088.mp3" },
  { "id": 89, "name": "الفجر", "url": "https://server10.mp3quran.net/minsh/089.mp3" },
  { "id": 90, "name": "البلد", "url": "https://server10.mp3quran.net/minsh/090.mp3" },
  { "id": 91, "name": "الشمس", "url": "https://server10.mp3quran.net/minsh/091.mp3" },
  { "id": 92, "name": "الليل", "url": "https://server10.mp3quran.net/minsh/092.mp3" },
  { "id": 93, "name": "الضحى", "url": "https://server10.mp3quran.net/minsh/093.mp3" },
  { "id": 94, "name": "الشرح", "url": "https://server10.mp3quran.net/minsh/094.mp3" },
  { "id": 95, "name": "التين", "url": "https://server10.mp3quran.net/minsh/095.mp3" },
  { "id": 96, "name": "العلق", "url": "https://server10.mp3quran.net/minsh/096.mp3" },
  { "id": 97, "name": "القدر", "url": "https://server10.mp3quran.net/minsh/097.mp3" },
  { "id": 98, "name": "البينة", "url": "https://server10.mp3quran.net/minsh/098.mp3" },
  { "id": 99, "name": "الزلزلة", "url": "https://server10.mp3quran.net/minsh/099.mp3" },
  { "id": 100, "name": "العاديات", "url": "https://server10.mp3quran.net/minsh/100.mp3" },
  { "id": 101, "name": "القارعة", "url": "https://server10.mp3quran.net/minsh/101.mp3" },
  { "id": 102, "name": "التكاثر", "url": "https://server10.mp3quran.net/minsh/102.mp3" },
  { "id": 103, "name": "العصر", "url": "https://server10.mp3quran.net/minsh/103.mp3" },
  { "id": 104, "name": "الهمزة", "url": "https://server10.mp3quran.net/minsh/104.mp3" },
  { "id": 105, "name": "الفيل", "url": "https://server10.mp3quran.net/minsh/105.mp3" },
  { "id": 106, "name": "قريش", "url": "https://server10.mp3quran.net/minsh/106.mp3" },
  { "id": 107, "name": "الماعون", "url": "https://server10.mp3quran.net/minsh/107.mp3" },
  { "id": 108, "name": "الكوثر", "url": "https://server10.mp3quran.net/minsh/108.mp3" },
  { "id": 109, "name": "الكافرون", "url": "https://server10.mp3quran.net/minsh/109.mp3" },
  { "id": 110, "name": "النصر", "url": "https://server10.mp3quran.net/minsh/110.mp3" },
  { "id": 111, "name": "المسد", "url": "https://server10.mp3quran.net/minsh/111.mp3" },
  { "id": 112, "name": "الإخلاص", "url": "https://server10.mp3quran.net/minsh/112.mp3" },
  { "id": 113, "name": "الفلق", "url": "https://server10.mp3quran.net/minsh/113.mp3" },
  { "id": 114, "name": "الناس", "url": "https://server10.mp3quran.net/minsh/114.mp3" }
]

export const sheikhAlMinshawi = {
  name: "الشيخ محمد صديق المنشاوي",
  fullName: "محمد صديق أبو محمد عبدالعزيز حسن المنشاوي",
  birth: {
    date: "20 يناير 1920",
    place: "المنشاة، محافظة سوهاج، مصر"
  },
  death: {
    date: "20 يونيو 1969",
    age: 49,
    cause: "دوالي المريء"
  },
  family: {
    father: "الشيخ صديق المنشاوي (قارئ ومعلّم قرآن)",
    grandfather: "الشيخ تايب المنشاوي (من أشهر قرّاء الصعيد)",
    childrenCount: 15,
    marriages: [
      {
        wifeOrder: 1,
        children: { sons: 4, daughters: 2 }
      },
      {
        wifeOrder: 2,
        children: { sons: 5, daughters: 4 },
        notes: "توفيت الزوجة الثانية أثناء الحج قبل وفاة الشيخ بعام تقريبًا"
      }
    ]
  },
  education: {
    memorizedQuranAt: "عمر 8 سنوات تقريبًا",
    teachers: [
      "أهل عائلته من القرّاء",
      "عدد من مشايخ المنشاة",
      "مشايخ القاهرة بعد انتقاله إليها"
    ],
    recitationSchool: "تجويد على الطريقة المصرية التقليدية"
  },
  career: {
    occupation: "قارئ قرآن معتمد في الإذاعة المصرية",
    style: "خشوع وتأثر شديد — لُقب بالصوت الباكي",
    achievements: [
      "تسجيل المصحف المرتل كاملًا برواية حفص عن عاصم",
      "تسجيل أجزاء كبيرة من المصحف المجود",
      "إحياء أمسيات قرآنية في مصر والعالم العربي",
      "إسهام كبير في نشر علوم التلاوة"
    ],
    famousQuotes: [
      {
        by: "الشيخ محمد متولي الشعراوي",
        quote: "من أراد أن يستمع إلى خشوع القرآن فليستمع لصوت المنشاوي."
      }
    ],
    countriesVisited: [
      "السعودية",
      "سوريا",
      "الكويت",
      "ليبيا",
      "إندونيسيا",
      "الأردن",
      "فلسطين (المسجد الأقصى)",
      "الإمارات"
    ]
  },
  titles: [
    "الصوت الباكي",
    "قارىء القلوب",
    "أحد أعلام مدرسة التلاوة المصرية"
  ],
  legacy: {
    impact: [
      "مدرسة كاملة من القرّاء تأثروا بأسلوبه",
      "مرجع في الخشوع والتجويد",
      "تسجيلات تُدرّس وتُستخدم إلى اليوم في تحفيظ القرآن"
    ],
    knownFor: [
      "الإحساس العالي بالمعنى",
      "الخشوع الشديد",
      "جودة الأحكام",
      "المدرسة المنشاوية في الأداء"
    ]
  },

  // ✅ ملخص موسع عن حياته ومسيرته
  summary: {
    paragraph1:
      "وُلِد الشيخ محمد صديق المنشاوي في بيئة قرآنية خالصة، شكّلت وجدانه منذ نعومة أظفاره، فقد نشأ في بيت اشتهر بحفظ القرآن وتجويده، وكان والده وجده من أبرز القرّاء في صعيد مصر. هذا الجو الإيماني كان له أثر كبير في تشكيل شخصيته، فحفظ القرآن الكريم وهو في سن مبكرة، وتعلّم على يد كبار المشايخ أصول التلاوة وأحكام التجويد، ليشبَّ راسخ القدم في علوم القرآن، مؤمنًا برسالته، مُخلصًا في أدائه، متنفسًا بالقرآن قبل أي شيء آخر.",

    paragraph2:
      "بدأت مسيرته العملية مع القرآن مبكرًا، فكان يُدعَى لقراءة القرآن في المناسبات والاحتفالات الدينية في محافظات الصعيد، ثم ذاع صيته شيئًا فشيئًا حتى وصلت شهرته إلى القاهرة، فانتقل إليها ليبدأ مرحلة جديدة أكثر انتشارًا وتأثيرًا. وقد تم اعتماده قارئًا في الإذاعة المصرية، وهناك بدأت رحلة التسجيل الإذاعي التي خلّدته في ذاكرة المستمعين، فقرأ المصحف المرتل كاملًا، وترك تسجيلات مجودة لا تزال تُبث في الإذاعات ومحطات التلفاز حتى يومنا هذا.",

    paragraph3:
      "امتاز الشيخ المنشاوي بصوت فريد من نوعه، يجمع بين قوة الأداء، وصدق الإحساس، ورهافة المشاعر التي تجعل المستمعين يعيشون معاني الآيات وكأنها تُتلى لأول مرة. ولشدة تأثره، ولعمق خشوعه، أطلق عليه الكثيرون لقب 'الصوت الباكي'. لم تكن قراءته أداءً صوتيًا فقط، بل كانت رسالة روحية، تبث السكينة في النفوس، وتُعيد للقلوب حياةً بعد جفاف. سافر إلى كثير من الدول العربية والإسلامية، وقرأ في مساجد عظيمة ومسارح دولية، وكان ممثلاً لمصر في المحافل القرآنية الكبرى.",

    paragraph4:
      "لم تكن حياة الشيخ خالية من التحديات، فقد ابتُلي في آخر حياته بمرض شديد أضعف جسده، لكنه ظلّ مُصِرًا على العطاء والتلاوة حتى آخر أيامه. ورحل عن الدنيا في سنٍ صغيرة نسبياً، لكنه ترك أثرًا لا يمحوه الزمن، ومدرسة كاملة في التلاوة تُدرَّس وتُقتدى. ويُعتبر اليوم واحدًا من أعظم قرّاء القرآن في العصر الحديث، وصوته يواصل التأثير في الملايين حول العالم، ليبقى إرثه القرآني شاهدًا على إخلاصه وصدقه وتفانيه في خدمة كتاب الله تعالى."
  }
};


export const videos = [
  {
    "title": "لقاء نادر جدا مع الشيخ محمد صديق المنشاوى قبيل وفاته بعامين | جودة عالية HD",
    "youtubeUrl": "https://youtu.be/9UolmRufK4E?si=8EQbf4fyCqxtN6D9",
    "thumbnail": "https://i.ytimg.com/vi/9UolmRufK4E/hq720.jpg",
    "duration": "14:15",
    "category": "documentary"
  },
  {
    "title": "مقابلة نادرة ١٩٦٧م مع فضيلة الشيخ محمد صديق المنشاوي رحمه الله",
    "youtubeUrl": "https://youtu.be/heEgiDnMEzI?si=lTMnNksp4MaaR6nP",
    "thumbnail": "https://i.ytimg.com/vi/heEgiDnMEzI/hq720.jpg",
    "duration": "08:32",
    "category": "documentary"
  },
  {
    "title": "من ذروة روائعه الخالدة | تلاوة أسطورية لسورة آل عمران تهز الوجدان | الشيخ المنشاوي 🎧",
    "youtubeUrl": "https://youtu.be/Dy84Tfn6gQ4?si=CxYxidgXWuQJP7Kr",
    "thumbnail": "https://i.ytimg.com/vi/Dy84Tfn6gQ4/hq720.jpg",
    "duration": "48:20",
    "category": "rare"
  },
  {
    "title": "سورة الحشر والطارق والضحى والشرح - تلاوة تاريخية أسطورية من مسجد السيدة زينب عام 1960",
    "youtubeUrl": "https://www.youtube.com/watch?v=F0k9yD4eK0E",
    "thumbnail": "https://i.ytimg.com/vi/F0k9yD4eK0E/hq720.jpg",
    "duration": "59:45",
    "category": "mosque"
  },
  {
    "title": "تلاوة تفوق الوصف لسورتي يوسف والرعد - تلاوة نادرة جدا للشيخ محمد صديق المنشاوي",
    "youtubeUrl": "https://www.youtube.com/watch?v=vVj4Z6H6fL4",
    "thumbnail": "https://i.ytimg.com/vi/vVj4Z6H6fL4/hq720.jpg",
    "duration": "43:10",
    "category": "rare"
  },
  {
    "title": "الفيلم الوثائقي النادر: حياة الشيخ محمد صديق المنشاوي وصوت السماء الخالد",
    "youtubeUrl": "https://www.youtube.com/watch?v=l_a1RypE30E",
    "thumbnail": "https://i.ytimg.com/vi/l_a1RypE30E/hq720.jpg",
    "duration": "24:50",
    "category": "documentary"
  }
];
